### ISSUE TITLE
additional addon not added to repo

### ISSUE THREAD

**Issue by mytvpro** [ping/instant-kodi-repo#1]
is this only supposed to work with one addon? i have added plugin.video.foo but it doesn't display in my repo and is not inlcuded in master addon.xml

**Comment by mytvpro** [comment]
apologies i'm checking it out in travis-cli some stupid git mistake of mine made building fail

**Comment by mytvpro** [comment]
wait i'm wrong it wasn't a git error. the error i'm getting says invalid addon version and it names the version i have defined in the addon.xml... i have 1.0 before that it said 5.0 either way it says invalid... don't understand why

**Comment by mytvpro** [comment]
apologies again. there is something i just don't understand fundamentally i guess. i changed the version 1.0.1 and it worked. don't know why though. i only did it to be consistent with version numbering used on hello world and the repo itself...

**Comment by mytvpro** [comment]
now i changed the add-on id and getting error about that. can't get passed it successful build

**Comment by ping** [comment]
Where are your error logs?

Your add on ID must contain only a-z 0-9 . _ -
No upper case letters.

https://github.com/chadparry/kodi-repository.chad.parry.org/blob/master/tools/create_repository.py#L114-L115
