### ISSUE TITLE
kodi addon wont update

### ISSUE THREAD

**Issue by mytvpro** [ping/instant-kodi-repo#2]
ok so yeah i was using upper case in my addon id and probably invalid format for version number. my repo and addons are building again. but my addon wont update. i have changed the name and version number and it appears to be sucessful every where accpet for kodi. kodi still is showing an old version that isn't working. repo has version 1.0.2 but kodi still shows 1.0.1 would you have a suggestion please?

**Comment by ping** [comment]
This is a Kodi usage question and unrelated to this project.

You can either force a "Check for Updates" on the addon repo in Kodi, or just restart Kodi.

**Comment by mytvpro** [comment]
i had done both things but still doesn't show the updated addon. typically kodi would so that's why i thought it is related

**Comment by mytvpro** [comment]
jesus never mind it is showing correctly now sorry
