### ISSUE TITLE
repo fanart

### ISSUE THREAD

**Issue by mytvpro** [ping/instant-kodi-repo#3]
hello do you know how to add fanart to the repo template? i don't understand python enough to do it :(

**Comment by ping** [comment]
This is better asked in the [kodi forums](https://forum.kodi.tv/forumdisplay.php?fid=26).

**Comment by mytvpro** [comment]
It's very simple to add fanart to an addon.xml I don't know how to add code to the template in your instant Kodi repo that will put fanart into the repo like it does with the icon and also add it into the XML it makes. I don't think that would be found in a Kodi forum?

**Comment by ping** [comment]
Added support for fanart in ef886cfbd5868df10d1227d6972b3a3c159d3ab7

You have to add ``.github/templates/fanart.jpg`` to your repo which will be picked up when the repo addon is built.

**Comment by mytvpro** [comment]
Hello I have made my files look like yours and added fanart.jpg but it doesn't display. Is the fault mine? Have you tested it?

**Comment by ping** [comment]
Additional fix 52ad0f0c0e6634b98d12ec2c0e7d86f70584c7b0
